import type { Metadata } from "next";
import "./globals.css";

// Fonts are defined via local @font-face in globals.css to avoid network fetches during build.

export const metadata: Metadata = {
  title: "Course Browser",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="site-header">
          <img
            src="/logo.svg"
            alt="Loomis Chaffee"
            className="site-wordmark"
          />
        </header>
        {children}
      </body>
    </html>
  );
}
